name: new-action
on: push  

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello world"
      - name: say Goodbye
        run: echo "good bye"
      
